import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1774012181110 implements MigrationInterface {
    name = 'AutoMigration1774012181110'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "candidate_profiles" DROP CONSTRAINT "candidate_profiles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "resumes" DROP CONSTRAINT "resumes_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "question_banks" DROP CONSTRAINT "question_banks_company_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "question_banks" DROP CONSTRAINT "question_banks_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "job_listings" DROP CONSTRAINT "job_listings_company_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "job_listings" DROP CONSTRAINT "job_listings_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_company_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_job_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_resume_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_status_changed_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "application_comments" DROP CONSTRAINT "application_comments_company_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "application_comments" DROP CONSTRAINT "application_comments_job_application_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "application_comments" DROP CONSTRAINT "application_comments_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "company_members" DROP CONSTRAINT "company_members_company_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "company_members" DROP CONSTRAINT "company_members_invited_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "company_members" DROP CONSTRAINT "company_members_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resumes_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."unique_primary_resume_per_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_question_banks_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_visibility"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_applications_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_applications_job_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_applications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_applications_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_application_comments_application_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_company_members_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_company_members_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_is_read"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_job_id_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "company_members" DROP CONSTRAINT "company_members_company_id_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resumes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resumes" ALTER COLUMN "is_primary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "question_banks" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "question_banks" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."job_application_mode_enum" RENAME TO "job_application_mode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."job_listings_application_mode_enum" AS ENUM('STANDARD', 'QUESTIONNAIRE', 'VIDEO')`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" TYPE "public"."job_listings_application_mode_enum" USING "application_mode"::"text"::"public"."job_listings_application_mode_enum"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" SET DEFAULT 'STANDARD'`);
        await queryRunner.query(`DROP TYPE "public"."job_application_mode_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" SET DEFAULT 'STANDARD'`);
        await queryRunner.query(`ALTER TYPE "public"."job_visibility_enum" RENAME TO "job_visibility_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."job_listings_visibility_enum" AS ENUM('PUBLIC', 'PRIVATE')`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" TYPE "public"."job_listings_visibility_enum" USING "visibility"::"text"::"public"."job_listings_visibility_enum"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" SET DEFAULT 'PUBLIC'`);
        await queryRunner.query(`DROP TYPE "public"."job_visibility_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."job_status_enum" RENAME TO "job_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."job_listings_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'CLOSED')`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" TYPE "public"."job_listings_status_enum" USING "status"::"text"::"public"."job_listings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."job_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."application_status_enum" RENAME TO "application_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."job_applications_status_enum" AS ENUM('APPLIED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN')`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" TYPE "public"."job_applications_status_enum" USING "status"::"text"::"public"."job_applications_status_enum"`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" SET DEFAULT 'APPLIED'`);
        await queryRunner.query(`DROP TYPE "public"."application_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_comments" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_comments" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."company_role_enum" RENAME TO "company_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."company_members_role_enum" AS ENUM('OWNER', 'ADMIN', 'RECRUITER')`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "role" TYPE "public"."company_members_role_enum" USING "role"::"text"::"public"."company_members_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."company_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."member_status_enum" RENAME TO "member_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."company_members_status_enum" AS ENUM('ACTIVE', 'INVITED', 'REVOKED')`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" TYPE "public"."company_members_status_enum" USING "status"::"text"::"public"."company_members_status_enum"`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."member_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_dce6e1ce26d348e602f56fa636" ON "resumes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8f2140d3a6041e0d073dc13a6" ON "question_banks" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7045666726b664031a86819e1" ON "job_listings" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f0defe67873e415f4b9342127" ON "job_listings" ("visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_924b81ab61636e544696be4cfc" ON "job_listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_99292c6cd0ed428e8f5b4e2295" ON "job_applications" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bf4f05ce72bb2a329d8786194" ON "job_applications" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcfc78a3be953dac2443b9b53d" ON "job_applications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f2d5f25a87c7f6a6ab3e5f4dc" ON "job_applications" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8a682e449882ec67247746f89c" ON "job_applications" ("job_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0546aa0eb32bb86ec3179b235" ON "application_comments" ("job_application_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a796518fe32561cbabcb7df719" ON "application_comments" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6391779b147dac85c4788ed4f8" ON "application_comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e33a61fd560f6412d3ffb39f22" ON "company_members" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_535b42b6c7557886fd1c44501e" ON "company_members" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6e865dcafa308a5a7825d8de5c" ON "company_members" ("company_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12148ce379462ebbb4d06cc13" ON "notifications" ("is_read") `);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" ADD CONSTRAINT "FK_5a3673f11918bcea56f48549603" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resumes" ADD CONSTRAINT "FK_dce6e1ce26d348e602f56fa6363" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_banks" ADD CONSTRAINT "FK_c8f2140d3a6041e0d073dc13a65" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_banks" ADD CONSTRAINT "FK_0b4c3a3e40dbf8466e8c5d0fd57" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_listings" ADD CONSTRAINT "FK_f7045666726b664031a86819e15" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_listings" ADD CONSTRAINT "FK_04f6bb141aba3f8660a760355a6" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_99292c6cd0ed428e8f5b4e22958" FOREIGN KEY ("job_id") REFERENCES "job_listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_4bf4f05ce72bb2a329d87861942" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_fcfc78a3be953dac2443b9b53db" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_a6fbcb5a562d99321e5f5492521" FOREIGN KEY ("resume_id") REFERENCES "resumes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_381a6501b546dc4c2aabcddaef3" FOREIGN KEY ("status_changed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_comments" ADD CONSTRAINT "FK_e0546aa0eb32bb86ec3179b2356" FOREIGN KEY ("job_application_id") REFERENCES "job_applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_comments" ADD CONSTRAINT "FK_a796518fe32561cbabcb7df7196" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_comments" ADD CONSTRAINT "FK_6391779b147dac85c4788ed4f82" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_members" ADD CONSTRAINT "FK_e33a61fd560f6412d3ffb39f225" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_members" ADD CONSTRAINT "FK_535b42b6c7557886fd1c44501e4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_members" ADD CONSTRAINT "FK_b80d3c9b17156a3cb322a14c6ac" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "company_members" DROP CONSTRAINT "FK_b80d3c9b17156a3cb322a14c6ac"`);
        await queryRunner.query(`ALTER TABLE "company_members" DROP CONSTRAINT "FK_535b42b6c7557886fd1c44501e4"`);
        await queryRunner.query(`ALTER TABLE "company_members" DROP CONSTRAINT "FK_e33a61fd560f6412d3ffb39f225"`);
        await queryRunner.query(`ALTER TABLE "application_comments" DROP CONSTRAINT "FK_6391779b147dac85c4788ed4f82"`);
        await queryRunner.query(`ALTER TABLE "application_comments" DROP CONSTRAINT "FK_a796518fe32561cbabcb7df7196"`);
        await queryRunner.query(`ALTER TABLE "application_comments" DROP CONSTRAINT "FK_e0546aa0eb32bb86ec3179b2356"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_381a6501b546dc4c2aabcddaef3"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_a6fbcb5a562d99321e5f5492521"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_fcfc78a3be953dac2443b9b53db"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_4bf4f05ce72bb2a329d87861942"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_99292c6cd0ed428e8f5b4e22958"`);
        await queryRunner.query(`ALTER TABLE "job_listings" DROP CONSTRAINT "FK_04f6bb141aba3f8660a760355a6"`);
        await queryRunner.query(`ALTER TABLE "job_listings" DROP CONSTRAINT "FK_f7045666726b664031a86819e15"`);
        await queryRunner.query(`ALTER TABLE "question_banks" DROP CONSTRAINT "FK_0b4c3a3e40dbf8466e8c5d0fd57"`);
        await queryRunner.query(`ALTER TABLE "question_banks" DROP CONSTRAINT "FK_c8f2140d3a6041e0d073dc13a65"`);
        await queryRunner.query(`ALTER TABLE "resumes" DROP CONSTRAINT "FK_dce6e1ce26d348e602f56fa6363"`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" DROP CONSTRAINT "FK_5a3673f11918bcea56f48549603"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12148ce379462ebbb4d06cc13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e865dcafa308a5a7825d8de5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_535b42b6c7557886fd1c44501e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e33a61fd560f6412d3ffb39f22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6391779b147dac85c4788ed4f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a796518fe32561cbabcb7df719"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0546aa0eb32bb86ec3179b235"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a682e449882ec67247746f89c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f2d5f25a87c7f6a6ab3e5f4dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcfc78a3be953dac2443b9b53d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bf4f05ce72bb2a329d8786194"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99292c6cd0ed428e8f5b4e2295"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_924b81ab61636e544696be4cfc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f0defe67873e415f4b9342127"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7045666726b664031a86819e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8f2140d3a6041e0d073dc13a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dce6e1ce26d348e602f56fa636"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."member_status_enum_old" AS ENUM('ACTIVE', 'INVITED', 'REVOKED')`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" TYPE "public"."member_status_enum_old" USING "status"::"text"::"public"."member_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."company_members_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."member_status_enum_old" RENAME TO "member_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."company_role_enum_old" AS ENUM('OWNER', 'ADMIN', 'RECRUITER')`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "role" TYPE "public"."company_role_enum_old" USING "role"::"text"::"public"."company_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."company_members_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."company_role_enum_old" RENAME TO "company_role_enum"`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_members" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_comments" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_comments" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."application_status_enum_old" AS ENUM('APPLIED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN')`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" TYPE "public"."application_status_enum_old" USING "status"::"text"::"public"."application_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "status" SET DEFAULT 'APPLIED'`);
        await queryRunner.query(`DROP TYPE "public"."job_applications_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."application_status_enum_old" RENAME TO "application_status_enum"`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_applications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."job_status_enum_old" AS ENUM('DRAFT', 'ACTIVE', 'CLOSED')`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" TYPE "public"."job_status_enum_old" USING "status"::"text"::"public"."job_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."job_listings_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."job_status_enum_old" RENAME TO "job_status_enum"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."job_visibility_enum_old" AS ENUM('PUBLIC', 'PRIVATE')`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" TYPE "public"."job_visibility_enum_old" USING "visibility"::"text"::"public"."job_visibility_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "visibility" SET DEFAULT 'PUBLIC'`);
        await queryRunner.query(`DROP TYPE "public"."job_listings_visibility_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."job_visibility_enum_old" RENAME TO "job_visibility_enum"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."job_application_mode_enum_old" AS ENUM('STANDARD', 'QUESTIONNAIRE', 'VIDEO')`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "application_mode" TYPE "public"."job_application_mode_enum_old" USING "application_mode"::"text"::"public"."job_application_mode_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."job_listings_application_mode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."job_application_mode_enum_old" RENAME TO "job_application_mode_enum"`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job_listings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "question_banks" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "question_banks" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resumes" ALTER COLUMN "is_primary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resumes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_members" ADD CONSTRAINT "company_members_company_id_user_id_key" UNIQUE ("company_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "job_applications_job_id_user_id_key" UNIQUE ("job_id", "user_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_is_read" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_company_members_user_id" ON "company_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_company_members_company_id" ON "company_members" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "idx_application_comments_application_id" ON "application_comments" ("job_application_id") `);
        await queryRunner.query(`CREATE INDEX "idx_job_applications_status" ON "job_applications" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_job_applications_user_id" ON "job_applications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_job_applications_job_id" ON "job_applications" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "idx_job_applications_company_id" ON "job_applications" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "idx_job_visibility" ON "job_listings" ("visibility") `);
        await queryRunner.query(`CREATE INDEX "idx_job_status" ON "job_listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_job_company_id" ON "job_listings" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "idx_question_banks_company_id" ON "question_banks" ("company_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique_primary_resume_per_user" ON "resumes" ("user_id") WHERE (is_primary = true)`);
        await queryRunner.query(`CREATE INDEX "idx_resumes_user_id" ON "resumes" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_members" ADD CONSTRAINT "company_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_members" ADD CONSTRAINT "company_members_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_members" ADD CONSTRAINT "company_members_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_comments" ADD CONSTRAINT "application_comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_comments" ADD CONSTRAINT "application_comments_job_application_id_fkey" FOREIGN KEY ("job_application_id") REFERENCES "job_applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_comments" ADD CONSTRAINT "application_comments_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "job_applications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "job_applications_status_changed_by_fkey" FOREIGN KEY ("status_changed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "job_applications_resume_id_fkey" FOREIGN KEY ("resume_id") REFERENCES "resumes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "job_applications_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "job_listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "job_applications_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_listings" ADD CONSTRAINT "job_listings_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_listings" ADD CONSTRAINT "job_listings_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_banks" ADD CONSTRAINT "question_banks_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_banks" ADD CONSTRAINT "question_banks_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resumes" ADD CONSTRAINT "resumes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" ADD CONSTRAINT "candidate_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
